apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: fraud-api-pod-monitoring
  namespace: default
spec:
  selector:
    matchLabels:
      app: fraud-api
  endpoints:
    - port: 8000
      path: /metrics
      interval: 30s