apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-api-ksa
  namespace: default
  annotations:
    # Bind KSA với GSA qua Workload Identity
    iam.gke.io/gcp-service-account: fraud-api-sa@fraud-detection-493811.iam.gserviceaccount.com