name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - "data/raw/**"
      - "src/data/**"
      - "src/features/**"
      - "src/model/**"
      - "configs/**"
      - "params.yaml"
      - "params.ci.yaml"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Sync environment
        run: uv sync

      - name: Check DVC pipeline
        run: |
          test -f dvc.yaml
          uv run dvc dag

      - name: Switch to CI sample params
        run: |
          cp params.ci.yaml params.yaml

      - name: Run pipeline on small sample data
        run: |
          uv run dvc repro --force
